package com.mashibing.serviceverificationcode;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableDiscoveryClient
public class ServiceVerificationcodeApplication {

	public static void main(String[] args) {
		SpringApplication.run(ServiceVerificationcodeApplication.class, args);
	}

}
