server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-price
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0